- hosts: all
  gather_facts: yes
  tasks:
    - name: Erstelle ~/ansible-test.txt mit Inhalt "ok"
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME | default(lookup('env','HOME')) }}/ansible-test.txt"
        content: "ok\n"
        mode: '0644'
